---
apiVersion: v1
data:
  flink-cdc.yaml: |-
      parallelism: 2
      schema.change.behavior: EVOLVE      
  mysql-to-starrocks.yaml: |-
    source:
      type: mysql
      hostname: ${DB_HOST}
      port: 3306
      username: admin
      password: starrocks
      tables: workshop_db .\.*
      server-id: 5400-5404
      server-time-zone: UTC
    
    sink:
      type: starrocks
      name: StarRocks Sink
      jdbc-url: jdbc:mysql://${STARROCKS_JDBC_HOST}:9030
      load-url: ${STARROCKS_LOAD_HOST}:8080
      username: root
      password: ""
      table.create.properties.replication_num: 1


    pipeline:
      name: Sync MySQL Database to StarRocks
      parallelism: 1    
      log.level: DEBUG
kind: ConfigMap
metadata:
  name: flink-cdc-pipeline-configmap
  namespace: flinkcdc